project:
  type: website
  output-dir: docs

website:
  title: "עדי קליניק"
  navbar:
    left:
      - href: index.qmd
        text: בית
      - href: treatments_types.qmd
        text: סוגי טיפולים
      - href: recommendations.qmd
        text: לקוחות
      - href: contact.qmd
        text: יצירת קשר

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    navbar:
      style: default
